name: Continuous Integration

on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.12'
  
jobs:
  test_and_check:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest mypy

      - name: 格式化代码
        run: black .
        
      - name: 查看目录结构
        run: dir

      - name: 运行测试
        run: |
          if (Test-Path "tests") {
            pytest tests/
          } else {
            Write-Host "No tests directory found"
          }
        
      - name: 类型检查
        run: mypy --strict --junit-xml=tests/mypy_output.xml .

        
      - name: 生成文档
        run: python docs/docs.py
        
      - name: 存储结果
        run: git tag -a "latest" -m "CI/CD 完成"
