name: Continuous Integration

on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.10'
  
jobs:
  test_and_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest mypy

      - name: 格式化代码
        run: black .
        
      - name: 运行测试
        run: pytest tests/
        
      - name: 类型检查
        run: mypy --strict --format junit=tests/mypy_output.xml .
        
      - name: 生成文档
        run: python docs/docs.py
        
      - name: 存储结果
